version: '3.8'

services:
  app:
    build: .
    container_name: vse-backend-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3307/vse_db
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - redis
      - prometheus
    networks:
      - vse-network
  prometheus:
    image: prom/prometheus:latest
    container_name: vse-prometheus
    ports:
      - "9091:9090" # Changed host port to 9091 to fix the "ports are not available" error
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - vse-network

  grafana:
    image: grafana/grafana:latest
    container_name: vse-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - vse-network

  redis:
    image: redis:7.2-alpine
    container_name: vse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - vse-network

volumes:
  grafana-data:
  redis-data:

networks:
  vse-network:
    driver: bridge
